### ISSUE TITLE
Add `owner` to okta_group table

### ISSUE THREAD

**Issue by securitygeneration** [turbot/steampipe-plugin-okta#132]
**References**
https://developer.okta.com/docs/api/openapi/okta-management/management/tag/GroupOwner/

**Comment by ParthaI** [comment]
Hello @securitygeneration, just a heads-up: we've added support for a new table named `okta_group_owner` in [this PR](https://github.com/turbot/steampipe-plugin-okta/pull/133). This table will list all the owners of groups.

I couldn't test it in my environment due to a lack of permissions.

It would be great if you could try it out from the PR branch `issue-132`.

Steps to build the plugin locally from the branch `issue-132`
- git clone https://github.com/turbot/steampipe-plugin-okta.git
- cd steampipe-plugin-okta
- git checkout `issue-132`
- Run `make`
- Run the query

Thanks

**Comment by securitygeneration** [comment]
Hi @ParthaI, thanks!

Getting this error:
```
> select * from okta_group_owner

Error: okta: parsing time "2023-09-26 12:18:57.0" as "2006-01-02T15:04:05Z07:00": cannot parse " 12:18:57.0" as "T" (SQLSTATE HV000)
```

**Comment by ParthaI** [comment]
Hello @securitygeneration,

Thank you so much for testing the PR. I have addressed the above error and pushed a fix in the same branch (`issue-132`). Could you please pull the latest changes from the branch and try running the query by building the plugin locally again?

**Comment by securitygeneration** [comment]
Still getting this error after doing a git pull and make:

`Error: okta: parsing time "2023-09-26 12:21:00.0" as "2006-01-02T15:04:05Z07:00": cannot parse " 12:21:00.0" as "T" (SQLSTATE HV000)`

**Comment by securitygeneration** [comment]
Still the same error

**Comment by ParthaI** [comment]
Hi @securitygeneration,

I apologize for the inconvenience. I have pushed some fixes to the `issue-132` branch to address the timestamp parsing issue.

Could you please pull the latest changes from the `issue-132` branch, rebuild the plugin locally, and run the query again? If possible, could you also share your log details from `~/.steampipe/logs/plugin-....`, making sure to remove any sensitive information?

Thank you!
